name: Release

on: workflow_dispatch

env:
  DOTNET_SDK_VERSION: "9.0.307"

run-name: "v${{DOTNET_SDK_VERSION}}"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: posinformatique/dotnet-sdk-extended
      REGISTRY: ghcr.io

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if Docker image exists
        run: |
          echo "Build the version '${{ env.DOTNET_SDK_VERSION }}'"
      # - name: Build and push (version)
      #   uses: docker/build-push-action@v6
      #   if: steps.check_image.outputs.exists == 'false'
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     platforms: linux/amd64
      #     tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DOTNET_SDK_VERSION }}
      #     build-args: |
      #       DOTNET_SDK_VERSION=${{ env.DOTNET_SDK_VERSION }}
      #     no-cache: true
      #     provenance: false
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ env.DOTNET_SDK_VERSION }}"
          name: "v${{ env.DOTNET_SDK_VERSION }}"
          body: |
            Initial version of the image with the following tools:
            - Node.js: v22.20.0 (LTS)
            - npm: 10.9.3
            - sqlcmd: 1.5.0

            Based on [mcr.microsoft.com/dotnet/sdk:306](https://mcr.microsoft.com/en-us/product/dotnet/sdk/about)
          draft: true
          prerelease: false
