name: Release

on: workflow_dispatch

env:
  DOTNET_SDK_VERSION: "9.0.307"

run-name: "v9.0.307"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    env:
      IMAGE_NAME: posinformatique/dotnet-sdk-extended
      REGISTRY: ghcr.io

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (version)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          platforms: linux/amd64
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DOTNET_SDK_VERSION }}
          build-args: |
            DOTNET_SDK_VERSION=${{ env.DOTNET_SDK_VERSION }}
          no-cache: true
          provenance: false

      - name: Get tools versions from Docker
        id: tools_versions
        run: |
          docker run --rm "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DOTNET_SDK_VERSION }}" /bin/bash -lc '
            echo "NODE_VERSION=${NODE_VERSION}"
            echo "NPM_VERSION=${NPM_VERSION}"
            echo "SQLCMD_VERSION=${SQLCMD_VERSION}"
          ' >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ env.DOTNET_SDK_VERSION }}"
          name: "v${{ env.DOTNET_SDK_VERSION }}"
          body: |
            Initial version of the image with the following tools:
            - Node.js: v${{ steps.tools_versions.outputs.NODE_VERSION }}
            - npm: v${{ steps.tools_versions.outputs.NPM_VERSION }}
            - sqlcmd: ${{ steps.tools_versions.outputs.SQLCMD_VERSION }}

            Based on [mcr.microsoft.com/dotnet/sdk:${{ env.DOTNET_SDK_VERSION }}](https://mcr.microsoft.com/en-us/product/dotnet/sdk/about)
          draft: true
          prerelease: false
