name: Release

on: workflow_dispatch

run-name: ${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        dotnet_sdk_version:
          - "9.0.306"
          - "9.0.307"

    env:
      IMAGE_NAME: posinformatique/dotnet-sdk-extended
      REGISTRY: ghcr.io

    steps:
      - name: Check if Docker image exists
        id: check_image
        run: |
          if docker manifest inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.dotnet_sdk_version }} > /dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Checkout repository
        uses: actions/checkout@v4
        if: steps.check_image.outputs.exists == 'false'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: steps.check_image.outputs.exists == 'false'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        if: steps.check_image.outputs.exists == 'false'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if Docker image exists
        run: |
          echo "Build the version '${{ matrix.dotnet_sdk_version }}'"
      # - name: Build and push (version)
      #   uses: docker/build-push-action@v6
      #   if: steps.check_image.outputs.exists == 'false'
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     platforms: linux/amd64
      #     tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.dotnet_sdk_version }}
      #     build-args: |
      #       DOTNET_SDK_VERSION=${{ matrix.dotnet_sdk_version }}
      #     no-cache: true
      #     provenance: false
